const dummySongs = [
  {
    name: 'Asking For A Friend',
    artist: 'CHVRCHES',
    duration: '5:04',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'He Said She Said',
    artist: 'CHVRCHES',
    duration: '3:09',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'California',
    artist: 'CHVRCHES',
    duration: '4:08',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'Violent Delights',
    artist: 'CHVRCHES',
    duration: '5:19',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'How Not To Drown (feat. Robert Smith)',
    artist: 'CHVRCHES',
    duration: '5:31',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'Final Girl',
    artist: 'CHVRCHES',
    duration: '4:29',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'Good Girls',
    artist: 'CHVRCHES',
    duration: '3:19',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'Lullabies',
    artist: 'CHVRCHES',
    duration: '3:44',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: 'Nightmares',
    artist: 'CHVRCHES',
    duration: '4:33',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
  {
    name: `Better If You Don't`,
    artist: 'CHVRCHES',
    duration: '3:31',
    cover: 'https://i.redd.it/hwiqn9qtkt271.jpg',
    album: 'Screen Violence',
  },
];
export default dummySongs;
